### ISSUE TITLE
Logging in .. failed, busy

### ISSUE THREAD

**Issue by Daxuli** [sleirsgoevy/ps4-hamachi#3]
Hi, after a first successful log in where I was able to create and delete a network, the following times that I have launched the app have resulted in the following message: 
Logging in .. failed, busy
I have tried closing and reopening the app, deleting and reinstalling it, but it hasn't worked again. Sometimes there will be a message displayed indicating me to run a command.

**Comment by sleirsgoevy** [comment]
To send logs:
1. Connect netcat to port 9998 on your ps4.
2. Launch the app, wait fot it to fail, close the app.
3. Copy all the logs and send them here.
I don't have any extra-sensoric abilities, so I can't diagnose your problem while knowing nothing.

**Comment by Daxuli** [comment]
Hi, thank you for your reply, here's the log that you asked for:
[hamachi_log.txt](https://github.com/sleirsgoevy/ps4-hamachi/files/5753971/hamachi_log.txt)

**Comment by sleirsgoevy** [comment]
So I figured out the root cause (it is `FATAL: strtol stub called`), now the question is how I can reproduce this locally. Could you pull the `/user/home/hamachi` directory via FTP and post it here?

**Comment by Daxuli** [comment]
Here's the files that you asked for:
[var.zip](https://github.com/sleirsgoevy/ps4-hamachi/files/5755011/var.zip)
There were some issues downloading the following files (`File not found`), so I just skipped over them:

> `/user/home/hamachi/var/run/logmein-hamachi/ipc.sock`
> `/user/home/hamachi/var/run/logmein-hamachi/hamachid.lock`

Looking at them from the FTP, they seem to have a size of 0KB

**Comment by sleirsgoevy** [comment]
Fixed in public.
