### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by andrea-ap** [sleirsgoevy/ps4-hamachi#7]
Hy, when i execute, have error login error, but, not ask me for login. Ps4 fat with 9.00

**Comment by sleirsgoevy** [comment]
Please run Mira and record logs by telnet'ing to port 9998 on your console. Then send logs here.

**Comment by andrea-ap** [comment]
> Please run Mira and record logs by telnet'ing to port 9998 on your console. Then send logs here.

But i use goldhen

**Comment by Gggoleden** [comment]
Hello, how to run on Goldenhen 9.00, the error writes.

**Comment by Gggoleden** [comment]
![Uploading 16405852753387013506696643224820.jpg…]()

**Comment by andrea-ap** [comment]
> Hello, how to run on Goldenhen 9.00, the error writes.

I run app with the connection, but I am not asked for my credentials and I get an error logging in failed

![1640595293284](https://user-images.githubusercontent.com/63066393/147454793-e9f06360-3edd-4b44-8706-ee5c2bd898f6.jpg)
d

**Comment by marcinmaster999** [comment]
This error on startup and login failed   SceSblAuthMgrGetSelfAuthInfoFake:425 : ealready (no valid authinfo)

**Comment by andrea-ap** [comment]
> This error on startup and login failed SceSblAuthMgrGetSelfAuthInfoFake:425 : ealready (no valid authinfo)

But, app not ask credential, how solve

**Comment by andrea-ap** [comment]
But app not ask user or password, how solve

Il lun 27 dic 2021, 13:43 marcinmaster999 ***@***.***> ha
scritto:

**Comment by Pietro395** [comment]
Same problem for me on 9.00: Logging in failed

**Comment by ELBartoPS4** [comment]
same for me but iam sure he is working on it ............. always do good things i can wait keep up your good work !!!

**Comment by xkoeckiiej** [comment]
Error logging in for me as well on 9.00

**Comment by aldo-o** [comment]
Same error. Logging in... failed. on 9.00.

**Comment by yigal33** [comment]
i ran the the up and get  "login in falid" im in 9.00 frimewre any fix ?

**Comment by jgbiw** [comment]
> Please run Mira and record logs by telnet'ing to port 9998 on your console. Then send logs here.

Having the same issue here, here are the logs. Thanks in advance.
[log.txt](https://github.com/sleirsgoevy/ps4-hamachi/files/7827646/log.txt)

**Comment by yigal33** [comment]
hi
sorry but i dont no how to do that
any guide?
thanks.

בתאריך יום ו׳, 7 בינו׳ 2022, 10:53, מאת jgbiw ***@***.***>:

**Comment by jgbiw** [comment]
@yigal33 I used WSL myself but I assume you don't have that nor Linux installed, so the first thing you have to do is enable telnet (https://social.technet.microsoft.com/wiki/contents/articles/38433.windows-10-enabling-telnet-client.aspx). If your PS4 is on and running GoldHEN, you'll have to restart it (rest/sleep mode won't work) and then run Mira instead of GoldHEN. Open a cmd window and enter "telnet <your PS4's IP> 9998" (no quotation marks and no <>) and the logs should show up. Now run the Hamachi/LogMeIn app and once you've gotten the error screen, copy the logs and paste them into a txt file.

**Comment by Saito197** [comment]
> @yigal33 I used WSL myself but I assume you don't have that nor Linux installed, so the first thing you have to do is enable telnet (https://social.technet.microsoft.com/wiki/contents/articles/38433.windows-10-enabling-telnet-client.aspx). If your PS4 is on and running GoldHEN, you'll have to restart it (rest/sleep mode won't work) and then run Mira instead of GoldHEN. Open a cmd window and enter "telnet <your PS4's IP> 9998" (no quotation marks and no <>) and the logs should show up. Now run the Hamachi/LogMeIn app and once you've gotten the error screen, copy the logs and paste them into a txt file.

How do you use Mira on 9.0.0?

**Comment by sleirsgoevy** [comment]
Everyone involved, please check whether it still fails on current version. If it now works, I think this issue should be closed.

**Comment by yigal33** [comment]
hi
for me its fixed from the last ver.
thanks

בתאריך שבת, 12 בפבר׳ 2022, 02:28, מאת sleirsgoevy ***@***.***

**Comment by jgbiw** [comment]
Works for me, thanks :)

**Comment by Saito197** [comment]
Working for me

**Comment by sleirsgoevy** [comment]
Then closing this for now. Feel free to reopen if this still happens.
